function selection = loadSelection(selectionPath, datasetIndex, cfg)
%LOADSELECTION Load a completed selection that matches this reconstruction.

selectionPath = string(selectionPath);
completionPath = fullfile(fileparts(selectionPath), "stage_complete.txt");
if ~isfile(selectionPath) || ~isfile(completionPath)
    error("stpt:TissueOtsuSelection", ...
        "Completed tissue-selection output is required: %s", selectionPath);
end

saved = load(selectionPath, "selection");
selection = saved.selection;
if selection.method ~= "tissueOtsu" || ...
        selection.referenceChannel ~= cfg.illumination.tissueReferenceChannel || ...
        ~isequal(selection.trainingSections, ...
        cfg.illumination.trainingSections(:)') || ...
        ~isequal(selection.cropPixels, cfg.preprocessing.cropPixels) || ...
        any(~ismember(selection.tiles.sectionNumber, ...
        [datasetIndex.sections.number]))
    error("stpt:TissueOtsuSelection", ...
        "Completed tissue selection does not match the current configuration.");
end
end
