function manifest = loadCompletedProduction( ...
        stageDir, datasetIndex, model, cfg)
%LOADCOMPLETEDPRODUCTION Validate and load the complete Stage 3 product.

requiredFiles = ["stage_complete.txt", "manifest.csv", ...
    "reconstruction_signature.mat"];
if ~isfolder(stageDir) || ...
        ~all(isfile(fullfile(stageDir, requiredFiles)))
    error("stpt:IncompleteReconstruction", ...
        "Completed production reconstruction is missing from %s.", stageDir);
end

saved = load(fullfile(stageDir, "reconstruction_signature.mat"), "signature");
expectedSignature = stpt.reconstruction.buildSignature( ...
    datasetIndex, model, cfg, cfg.processing.sections);
if ~isequaln(saved.signature, expectedSignature)
    error("stpt:StaleReconstruction", ...
        "Stage 3 production was built from different scientific inputs. " + ...
        "Rerun reconstructionProduction before downsampling.");
end

manifest = readtable(fullfile(stageDir, "manifest.csv"), ...
    "TextType", "string");
expectedPlanes = numel(cfg.processing.sections) * ...
    datasetIndex.geometry.layersPerSection * numel(datasetIndex.channels);
keys = unique(manifest(:, ["sectionNumber", "layer", "channelId"]), "rows");
if height(manifest) ~= expectedPlanes || height(keys) ~= expectedPlanes
    error("stpt:IncompleteReconstruction", ...
        "Stage 3 manifest does not contain the expected %d unique planes.", ...
        expectedPlanes);
end
if numel(unique(manifest.heightPixels)) ~= 1 || ...
        numel(unique(manifest.widthPixels)) ~= 1 || ...
        ~all(strcmpi(manifest.compression, "lzw"))
    error("stpt:IncompleteReconstruction", ...
        "Stage 3 TIFF dimensions or compression are inconsistent.");
end

for c = 1:numel(datasetIndex.channels)
    channelId = datasetIndex.channels(c).id;
    stpt.downsampling.buildPlaneList(manifest, channelId, ...
        cfg.processing.sections, datasetIndex.geometry.layersPerSection);
end
end
