function tile = prepareTile(datasetIndex, model, cfg, sectionNumber, ...
        layer, channelId, acquisitionIndex, gridY)
%PREPARETILE Load, crop, correct, and orient one native tile for fusion.

rawTile = stpt.io.loadTile(datasetIndex, sectionNumber, layer, ...
    acquisitionIndex, channelId);
tile = stpt.illumination.applyModel( ...
    rawTile, model, channelId, layer, gridY);
tile = stpt.preprocessing.applyTileOrientation( ...
    tile, cfg.preprocessing.tileOrientation);

if any(~isfinite(tile(:)))
    error("stpt:FusionIntensity", ...
        "Non-finite processed pixels in section %d, layer %d, ch%d.", ...
        sectionNumber, layer, channelId);
end
end
